compatibility_date = "2023-05-27"
main = "release/index.js"
name = "kuba-io"
send_metrics = false

[build]
command = "yarn build"
watch_dir = "src"

[dev]
ip = "localhost"
port = 5000

[site]
bucket = "assets"
