compatibility_date = "2023-05-27"
main = "release/index.js"
name = "kuba-io"
send_metrics = false

[build]
command = "yarn run swc src -d release"
watch_dir = "src"

[dev]
ip = "localhost"
port = 5000

[site]
bucket = "asset"
include = [
  "prelude"
]
