compatibility_date = "2023-05-27"
main = "dist/index.js"
name = "kuba-io"
send_metrics = false

[buid]
command = "yarn run tsc"
cwd = "."
watch_dir = "."

[site]
bucket = "public"

[dev]
ip = "localhost"
port = 5000
local_protocol = "http"
