compatibility_date = "2023-05-27"
main = "dist/index.js"
name = "kuba-io"
send_metrics = false

[site]
bucket = "public"

[build]
command = "yarn run tsc"
watch_dir = "src"

[dev]
ip = "localhost"
port = 5000
